disabled_rules:
  - trailing_whitespace
  
opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
included:
  - TheMovieDB
  - TheMovieDBTests
  - TheMovieDBUITests
excluded:
  - Pods
  - Project/R.generated.swift

force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4

type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 35
  excluded: iPhone 
reporter: "xcode"

